#!/bin/sh

# exit if any statement returns non-true return value
set -e

# exit on uninitialized variable
set -u

HTML_BASE=${buildout:directory}/docs/.build/html
BUILD_DIR=${buildout:directory}/build

cd ${buildout:directory}

[ -d $BUILD_DIR/docs/en ]
[ -d $BUILD_DIR/docs/ko ]

python setup.py upload_docs --upload-dir=$BUILD_DIR/docs
