#!/bin/sh

# exit if any statement returns non-true return value
set -e

# exit on uninitialized variable
set -u

SRC_DIR=${buildout:directory}/docs
POT_DIR=${buildout:directory}/docs/.build/gettext
PO_BASE=${buildout:directory}/docs/translated

${buildout:directory}/bin/sphinx-build -b gettext $SRC_DIR $POT_DIR

for LANG in ko en; do
for FILE in index intro hwp5proc converters; do
PO_FILE=$PO_BASE/$LANG/LC_MESSAGES/$FILE.po
POT_FILE=$POT_DIR/$FILE.pot
echo $PO_FILE
[ -e $PO_FILE ] && msgmerge --update $PO_FILE $POT_FILE
[ -e $PO_FILE ] || cp $POT_FILE $PO_FILE

done
done
